# Select image from https://hub.docker.com/_/php/
image: php:7.4.6

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Install git and unzip (composer will need them)
  - apt-get update && apt-get install -qqy git unzip
  # Install composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  # Install all project dependencies
  - composer install

# Test1
test1:
  script:
    - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*,*/Rapports/*

# Test2
test2:
  script:
    - vendor/bin/codecept run unit