# Select image from https://hub.docker.com/_/php/
image: php:7.4.6

before_script:
  # Install git and unzip (composer will need them)
  - apt-get update && apt-get install -qqy git unzip
  # Install composer
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  # Install all project dependencies
  - composer install

stages:
  - code_sniffer
  - codeception_unit

Code sniffer:
  stage: code_sniffer
  script: vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averroes_users --ignore=*/vendor/*,*/Tests/_output/*

Codeception unit:
  stage: codeception_unit
  script: vendor/bin/codecept run unit