language: php

dist: trusty

os: linux

jobs:
  include:
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - printf "\n" | pecl install yaml
  - travis_retry composer update

addons:
  sonarcloud:
    organization: "herradiamine"
    token:
      secure: "nBNTjoiC3/8oCl7aMcPFpc/Jgl3IlC8IR9YQgp3QnJIIVINPXXEYS1hjVpjMePURakvMD7A01cPiGI25JIn3j4SrBPdKUCwln5QtSBNy7WclG12Nw9BBD9vXmzxniriakYnwwCC2RzAn6nj+h9JVYONzbXuPWvxZaWfLF703Z/zYAesBdWyr/NH7JsZz0XEsD3rG3XgtZ3gU28T1XyG4o0nnf1gCKKt4W7Q5QOcL2v9U3MFYyGYOBPdbIMPF3eMafitXdU6VTjZgbAaflFQv39mbY2R9s0r+cnxyG5BQ3eRVK8CQ6uv23Hh8aIn0x5vcSSckZJaJqm6pinNzDCfIbU0I/66D8ABWPMY2JLxgcE3ZB+CH6OZ7gIFYFP4Jkmzv9RK+iMEgVbTSItph9yCjgwi991d2dSljOEQGjBk6px3rW8qiPqcXPNs0+z8SqjHp4YlgmK2/CZJcCLCjOyO+Ji6FRkwbH4izbtFR9AQVhnWDu1RVINlavziczrhIgqSAyXFuifYhYZWJMB3wUYW/tNIxawyD0Qa4E8TG5XdCzRVsNnDaSoMcZXMqkwdvedqEvGMIfrsYu63VWfsVEUJk/TjnU1DntXC0lS0DFdo3bDsEhdPD3sq1aVneqN+SnNNijJxrkunD7s0vY0F84MYoSGxfKjSjUo8LGclcKeK2enA="

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*,*/Rapports/*
  - vendor/bin/phpunit
  - sonar-scanner

notifications:
  email: herradiamine@gmail.com