language: php

dist: trusty

os: linux

jobs:
  include:
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - printf "\n" | pecl install yaml
  - travis_retry composer update
  - travis encrypt a62bd89f9f3e40b2376ea859149ea96dc0be4519

addons:
  sonarcloud:
    organization: "herradiamine"
    token:
      secure: "a62bd89f9f3e40b2376ea859149ea96dc0be4519"

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*,*/Rapports/*
  - vendor/bin/phpunit
  - sonar-scanner

notifications:
  email: herradiamine@gmail.com