language: php

dist: trusty

os: linux

jobs:
  include:
    - php: 7.3
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - apt install php-yaml
  - composer install --prefer-dist

install:
  - travis_retry composer update

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*