language: php

dist: trusty

os: linux

jobs:
  include:
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - printf "\n" | pecl install yaml
  - travis_retry composer update

addons:
  sonarcloud:
    organization: "herradiamine"
    token:
      secure: "90c9dfe0fd8d3b8d1d33d6bf135bf950897e7a12"

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*,*/Rapports/*
  - vendor/bin/phpunit
  - sonar-scanner

notifications:
  email: herradiamine@gmail.com