language: php

dist: trusty

os: linux

jobs:
  include:
  - php: 7.4

cache:
  directories:
  - "$HOME/.composer/cache"

before_script:
- composer install --prefer-dist

install:
- printf "\n" | pecl install yaml
- travis_retry composer update

script:
- vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*,*/Rapports/*
- vendor/bin/phpunit
- sonar-scanner

notifications:
  email: herradiamine@gmail.com

addons:
  sonarcloud:
    organization: herradiamine

env:
  global:
    secure: ffD87ThSDrtynrn3ASlpKSePZRdv/hebt3mIT3pDqhIomKNpFhlUvqGjwUA1fWCdRaJDu/2XFz/dsFDeUTZVBJE7u9FbmwxljrLm0HYFu4LGVE/Tyf1H0JAXkArZPNY3FJGZ0mfEirqJMvttFgdq44f89Fz31AGDFmrRwZQGOG1Sr8nB8mIHHiKZK6n5HzoY1fMyqLbU/uGrOalJylZzhlyi4bOew5Oy/5B2KAqyETwQzfIGUIj6m6pESJrqvDi8faJWf+030ozw/D/lPaNEP1BMfv8J1jJv3WDbRbg0JQPS99xUu4oDUs7jCSJHzWSJaHZxFkIo6Hdb2Z2kmctWikIY/cCiN/9s3LLjw5gWDuUBLdWFRZGw+skH83ulOWq4xNKBOBNn04vA/W39ubC5cigJ/+/GznxU+4WcHsh2ckEdBNM6nVLUmhCDf2rWmNelZcxkaTybRKBGU6OhVGBBtW7boARUy0BZdLbvrAb2aZdQYCu5TrKepBaQi3G3oX4/eCLtty8bYYUH82WIzXvLZev2jd55W3981AYk1nOr3P4M1PMaepDzG+RLRiveV+kyuiU4i8P6d9XHbceTTF/ednI5fgbMzRwBxhozuB3RZpsTFsuqaS8SP8Bi+JqkRNnWFOv2JRFpVegby0zLq5UpwjY0AKxsimDGw1XrUl7PkAM=
