language: php

dist: trusty

os: linux

jobs:
  include:
    - php: 7.3
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - printf "\n" | pecl install yaml
  - travis_retry composer update

script:
  - vendor/bin/phpcs --standard=PSR1,PSR2,PSR12 ../averoes_users --ignore=*/vendor/*

notifications:
  email:
    recipients:
      - herradiamine@gmail.com
      on_success: always
      on_failure: always